trigger FMPTargets on FMP_Target__c (before insert, before update) {
	if(checkRecursive.runOnce()){
		if (Trigger.isInsert) {

			for(FMP_Target__c newTarget : Trigger.new){
				List <FMP_Target__c> existingTargets = [Select FMP_Diagnostic__c From FMP_Target__c Where FMP_Diagnostic__c = :newTarget.FMP_Diagnostic__c];
				if(existingTargets.size()>0){
					newTarget.adderror('No puede volver a definir metas con esta encuesta, por favor use la encuesta de redefinición');
				}
			}
		}
		if (Trigger.isUpdate) {
			List <FMP_Target__c> targetsToUpdate = new List <FMP_Target__c>();
			for (FMP_Target__c upTarget: Trigger.new) {
				FMP_Target__c oldTarget = Trigger.oldMap.get(upTarget.Id);
				FMP_Target__c upsertarget = new FMP_Target__c ();
				upsertarget.Id= oldTarget.Id;
				upsertarget.adequateTransportation__c =(upTarget.adequateTransportation__c == 'Sí' && oldTarget.adequateTransportation__c == 'No')?upTarget.adequateTransportation__c:oldTarget.adequateTransportation__c;
				upsertarget.channelsScamperOk__c= (upTarget.channelsScamperOk__c == 'Sí' && oldTarget.channelsScamperOk__c == 'No')?upTarget.channelsScamperOk__c:oldTarget.channelsScamperOk__c;
				upsertarget.checklist__c = (upTarget.checklist__c == 'Sí' && oldTarget.checklist__c == 'No')?upTarget.checklist__c:oldTarget.checklist__c;
				upsertarget.coffeeDryingSystemOk__c = (upTarget.coffeeDryingSystemOk__c == 'Sí' && oldTarget.coffeeDryingSystemOk__c == 'No')?upTarget.coffeeDryingSystemOk__c:oldTarget.coffeeDryingSystemOk__c;
				upsertarget.coffeePackaging__c =(upTarget.coffeePackaging__c == 'Sí' && oldTarget.coffeePackaging__c == 'No')?upTarget.coffeePackaging__c:oldTarget.coffeePackaging__c;
				upsertarget.controlAccordingMonitoring__c = (upTarget.controlAccordingMonitoring__c == 'Sí' && oldTarget.controlAccordingMonitoring__c == 'No')?upTarget.controlAccordingMonitoring__c:oldTarget.controlAccordingMonitoring__c;
				upsertarget.evaluationPulping__c = (upTarget.evaluationPulping__c == 'Sí' && oldTarget.evaluationPulping__c == 'No')?upTarget.evaluationPulping__c:oldTarget.evaluationPulping__c;
				upsertarget.farmMap__c = (upTarget.farmMap__c== 'Sí' && oldTarget.farmMap__c == 'No')?upTarget.farmMap__c:oldTarget.farmMap__c;
				upsertarget.FaunaFloraRecoveryPlan__c = (upTarget.FaunaFloraRecoveryPlan__c == 'Sí' && oldTarget.FaunaFloraRecoveryPlan__c == 'No')?upTarget.FaunaFloraRecoveryPlan__c:oldTarget.FaunaFloraRecoveryPlan__c;
				upsertarget.fermentationTanksOk__c = (upTarget.fermentationTanksOk__c == 'Sí' && oldTarget.fermentationTanksOk__c == 'No')?upTarget.fermentationTanksOk__c:oldTarget.fermentationTanksOk__c;
				upsertarget.friendlyMethodsReducingHerbicide__c = (upTarget.friendlyMethodsReducingHerbicide__c == 'Sí' && oldTarget.friendlyMethodsReducingHerbicide__c == 'No')?upTarget.friendlyMethodsReducingHerbicide__c:oldTarget.friendlyMethodsReducingHerbicide__c;
				upsertarget.harvestEvaluation__c = (upTarget.harvestEvaluation__c == 'Sí' && oldTarget.harvestEvaluation__c == 'No')?upTarget.harvestEvaluation__c:oldTarget.harvestEvaluation__c;
				upsertarget.harvestRecord__c = (upTarget.harvestRecord__c == 'Sí' && oldTarget.harvestRecord__c == 'No')?upTarget.harvestRecord__c:oldTarget.harvestRecord__c;
				upsertarget.hasProtectionEquipment__c = (upTarget.hasProtectionEquipment__c == 'Sí' && oldTarget.hasProtectionEquipment__c == 'No')?upTarget.hasProtectionEquipment__c:oldTarget.hasProtectionEquipment__c;
				upsertarget.honeyWaterTreatmentTank__c = (upTarget.honeyWaterTreatmentTank__c == 'Sí' && oldTarget.honeyWaterTreatmentTank__c == 'No')?upTarget.honeyWaterTreatmentTank__c:oldTarget.honeyWaterTreatmentTank__c;
				upsertarget.identifyingErodedAreas__c = (upTarget.identifyingErodedAreas__c == 'Sí' && oldTarget.identifyingErodedAreas__c == 'No')?upTarget.identifyingErodedAreas__c:oldTarget.identifyingErodedAreas__c;
				upsertarget.implemetationSeedbedPlan__c = (upTarget.implemetationSeedbedPlan__c == 'Sí' && oldTarget.implemetationSeedbedPlan__c == 'No')?upTarget.implemetationSeedbedPlan__c:oldTarget.implemetationSeedbedPlan__c;
				upsertarget.knowledgeAreasLots__c = (upTarget.knowledgeAreasLots__c == 'Sí' && oldTarget.knowledgeAreasLots__c == 'No')?upTarget.knowledgeAreasLots__c:oldTarget.knowledgeAreasLots__c;
				upsertarget.knowledgeAreasLots__c = (upTarget.knowledgeAreasLots__c == 'Sí' && oldTarget.knowledgeAreasLots__c == 'No')?upTarget.knowledgeAreasLots__c:oldTarget.knowledgeAreasLots__c;
				upsertarget.makingMonitoringPestsDiseases__c = (upTarget.makingMonitoringPestsDiseases__c == 'Sí' && oldTarget.makingMonitoringPestsDiseases__c == 'No')?upTarget.makingMonitoringPestsDiseases__c:oldTarget.makingMonitoringPestsDiseases__c;
				upsertarget.monitoringRecordPestDisease__c = (upTarget.monitoringRecordPestDisease__c == 'Sí' && oldTarget.monitoringRecordPestDisease__c == 'No')?upTarget.monitoringRecordPestDisease__c:oldTarget.monitoringRecordPestDisease__c;
				upsertarget.postControlEvaluation__c = (upTarget.postControlEvaluation__c == 'Sí' && oldTarget.postControlEvaluation__c == 'No')?upTarget.postControlEvaluation__c:oldTarget.postControlEvaluation__c;
				upsertarget.properCoffeeStorage__c = (upTarget.properCoffeeStorage__c == 'Sí' && oldTarget.properCoffeeStorage__c == 'No')?upTarget.properCoffeeStorage__c:oldTarget.properCoffeeStorage__c;
				upsertarget.properSubstratesPreparation__c = (upTarget.properSubstratesPreparation__c == 'Sí' && oldTarget.properSubstratesPreparation__c == 'No')?upTarget.properSubstratesPreparation__c:oldTarget.properSubstratesPreparation__c;
				upsertarget.pulpCompostingPit__c= (upTarget.pulpCompostingPit__c == 'Sí' && oldTarget.pulpCompostingPit__c == 'No')?upTarget.pulpCompostingPit__c:oldTarget.pulpCompostingPit__c;
				upsertarget.pulpingMachineOk__c= (upTarget.pulpingMachineOk__c == 'Sí' && oldTarget.pulpingMachineOk__c == 'No')?upTarget.pulpingMachineOk__c:oldTarget.pulpingMachineOk__c;
				upsertarget.recordHarvesting__c= (upTarget.recordHarvesting__c == 'Sí' && oldTarget.recordHarvesting__c == 'No')?upTarget.recordHarvesting__c:oldTarget.recordHarvesting__c;
				upsertarget.recordOfLabor__c= (upTarget.recordOfLabor__c == 'Sí' && oldTarget.recordOfLabor__c == 'No')?upTarget.recordOfLabor__c:oldTarget.recordOfLabor__c;
				upsertarget.recordPesticideApplications__c= (upTarget.recordPesticideApplications__c == 'Sí' && oldTarget.recordPesticideApplications__c == 'No')?upTarget.recordPesticideApplications__c:oldTarget.recordPesticideApplications__c;
				upsertarget.recordPurchasingInputs__c= (upTarget.recordPurchasingInputs__c == 'Sí' && oldTarget.recordPurchasingInputs__c == 'No')?upTarget.recordPurchasingInputs__c:oldTarget.recordPurchasingInputs__c;
				upsertarget.recordsAgrochemicalsApplications__c= (upTarget.recordsAgrochemicalsApplications__c == 'Sí' && oldTarget.recordsAgrochemicalsApplications__c == 'No')?upTarget.recordsAgrochemicalsApplications__c:oldTarget.recordsAgrochemicalsApplications__c;
				upsertarget.recordSalesCPS__c= (upTarget.recordSalesCPS__c == 'Sí' && oldTarget.recordSalesCPS__c == 'No')?upTarget.recordSalesCPS__c:oldTarget.recordSalesCPS__c;
				upsertarget.recordVarietiesTreesPerLot__c= (upTarget.recordVarietiesTreesPerLot__c == 'Sí' && oldTarget.recordVarietiesTreesPerLot__c == 'No')?upTarget.recordVarietiesTreesPerLot__c:oldTarget.recordVarietiesTreesPerLot__c;
				upsertarget.recoveryErodedAreas__c= (upTarget.recoveryErodedAreas__c == 'Sí' && oldTarget.recoveryErodedAreas__c == 'No')?upTarget.recoveryErodedAreas__c:oldTarget.recoveryErodedAreas__c;
				upsertarget.reforestationNativeSpecies__c= (upTarget.reforestationNativeSpecies__c == 'Sí' && oldTarget.reforestationNativeSpecies__c == 'No')?upTarget.reforestationNativeSpecies__c:oldTarget.reforestationNativeSpecies__c;
				upsertarget.registrationWorkPerLot__c= (upTarget.registrationWorkPerLot__c == 'Sí' && oldTarget.registrationWorkPerLot__c == 'No')?upTarget.registrationWorkPerLot__c:oldTarget.registrationWorkPerLot__c;
				upsertarget.regulationOfShadow__c= (upTarget.regulationOfShadow__c == 'Sí' && oldTarget.regulationOfShadow__c == 'No')?upTarget.regulationOfShadow__c:oldTarget.regulationOfShadow__c;
				upsertarget.separationCoffeePerLot__c= (upTarget.separationCoffeePerLot__c == 'Sí' && oldTarget.separationCoffeePerLot__c == 'No')?upTarget.separationCoffeePerLot__c:oldTarget.separationCoffeePerLot__c;
				upsertarget.separationCoffeeQuality__c= (upTarget.separationCoffeeQuality__c == 'Sí' && oldTarget.separationCoffeeQuality__c == 'No')?upTarget.separationCoffeeQuality__c:oldTarget.separationCoffeeQuality__c;
			    	upsertarget.Submission__c = upTarget.Submission__c;
				upsertarget.tanksMucilageRemoverOk__c= (upTarget.tanksMucilageRemoverOk__c == 'Sí' && oldTarget.tanksMucilageRemoverOk__c == 'No')?upTarget.tanksMucilageRemoverOk__c:oldTarget.tanksMucilageRemoverOk__c;
				upsertarget.trainsStaffAgrochemicalsHandling__c= (upTarget.trainsStaffAgrochemicalsHandling__c == 'Sí' && oldTarget.trainsStaffAgrochemicalsHandling__c == 'No')?upTarget.trainsStaffAgrochemicalsHandling__c:oldTarget.trainsStaffAgrochemicalsHandling__c;
				upsertarget.transformationPulpsForUse__c= (upTarget.transformationPulpsForUse__c == 'Sí' && oldTarget.transformationPulpsForUse__c == 'No')?upTarget.transformationPulpsForUse__c:oldTarget.transformationPulpsForUse__c;
				upsertarget.useProtectionEquipment__c= (upTarget.useProtectionEquipment__c == 'Sí' && oldTarget.useProtectionEquipment__c == 'No')?upTarget.useProtectionEquipment__c:oldTarget.useProtectionEquipment__c;
				upsertarget.usingControlMethodsForPYE__c= (upTarget.usingControlMethodsForPYE__c == 'Sí' && oldTarget.usingControlMethodsForPYE__c == 'No')?upTarget.usingControlMethodsForPYE__c:oldTarget.usingControlMethodsForPYE__c;
				upsertarget.usingNativeSpeciesAsShading__c= (upTarget.usingNativeSpeciesAsShading__c == 'Sí' && oldTarget.usingNativeSpeciesAsShading__c == 'No')?upTarget.usingNativeSpeciesAsShading__c:oldTarget.usingNativeSpeciesAsShading__c;
				upsertarget.warehouseSafety__c= (upTarget.warehouseSafety__c == 'Sí' && oldTarget.warehouseSafety__c == 'No')?upTarget.warehouseSafety__c:oldTarget.warehouseSafety__c;
				upsertarget.wastewaterManagement__c= (upTarget.wastewaterManagement__c == 'Sí' && oldTarget.wastewaterManagement__c == 'No')?upTarget.wastewaterManagement__c:oldTarget.wastewaterManagement__c;
				upsertarget.wetmillSafety__c = (upTarget.wetmillSafety__c == 'Sí' && oldTarget.wetmillSafety__c == 'No')?upTarget.wetmillSafety__c:oldTarget.wetmillSafety__c;
				upsertarget.wetmillWaterManagement__c = (upTarget.wetmillWaterManagement__c == 'Sí' && oldTarget.wetmillWaterManagement__c == 'No')?upTarget.wetmillWaterManagement__c:oldTarget.wetmillWaterManagement__c;
				upsertarget.zarandaGoodCondition__c = (upTarget.zarandaGoodCondition__c == 'Sí' && oldTarget.zarandaGoodCondition__c == 'No')?upTarget.zarandaGoodCondition__c:oldTarget.zarandaGoodCondition__c;
				upsertarget.Biopreparations_Application__c= (upTarget.Biopreparations_Application__c != null && oldTarget.Biopreparations_Application__c == null)?upTarget.Biopreparations_Application__c:oldTarget.Biopreparations_Application__c;
				upsertarget.Broca_Traps__c= (upTarget.Broca_Traps__c != null && oldTarget.Broca_Traps__c == null)?upTarget.Broca_Traps__c:oldTarget.Broca_Traps__c;
				upsertarget.Buffer_Zones_Acequias__c= (upTarget.Buffer_Zones_Acequias__c != null && oldTarget.Buffer_Zones_Acequias__c == null)?upTarget.Buffer_Zones_Acequias__c:oldTarget.Buffer_Zones_Acequias__c;
				upsertarget.Buffer_Zones_Barrera_Viva__c= (upTarget.Buffer_Zones_Barrera_Viva__c != null && oldTarget.Buffer_Zones_Barrera_Viva__c == null)?upTarget.Buffer_Zones_Barrera_Viva__c:oldTarget.Buffer_Zones_Barrera_Viva__c;
				upsertarget.Buffer_Zones_Management__c= (upTarget.Buffer_Zones_Management__c != null && oldTarget.Buffer_Zones_Management__c == null)?upTarget.Buffer_Zones_Management__c:oldTarget.Buffer_Zones_Management__c;
				upsertarget.Chemical_Arana_Roja_Control__c= (upTarget.Chemical_Arana_Roja_Control__c != null && oldTarget.Chemical_Arana_Roja_Control__c == null)?upTarget.Chemical_Arana_Roja_Control__c:oldTarget.Chemical_Arana_Roja_Control__c;
				upsertarget.Chemical_Broca_Control__c= (upTarget.Chemical_Broca_Control__c != null && oldTarget.Chemical_Broca_Control__c == null)?upTarget.Chemical_Broca_Control__c:oldTarget.Chemical_Broca_Control__c;
				upsertarget.Chemical_Llaga_Control__c= (upTarget.Chemical_Llaga_Control__c != null && oldTarget.Chemical_Llaga_Control__c == null)?upTarget.Chemical_Llaga_Control__c:oldTarget.Chemical_Llaga_Control__c;
				upsertarget.Chemical_Ojo_de_Gallo_Control__c= (upTarget.Chemical_Ojo_de_Gallo_Control__c != null && oldTarget.Chemical_Ojo_de_Gallo_Control__c == null)?upTarget.Chemical_Ojo_de_Gallo_Control__c:oldTarget.Chemical_Ojo_de_Gallo_Control__c;
				upsertarget.Chemical_Roya_Control__c= (upTarget.Chemical_Roya_Control__c != null && oldTarget.Chemical_Roya_Control__c == null)?upTarget.Chemical_Roya_Control__c:oldTarget.Chemical_Roya_Control__c;
				upsertarget.Chemistry_Foliar_Fertilization__c= (upTarget.Chemistry_Foliar_Fertilization__c != null && oldTarget.Chemistry_Foliar_Fertilization__c == null)?upTarget.Chemistry_Foliar_Fertilization__c:oldTarget.Chemistry_Foliar_Fertilization__c;
				upsertarget.Chemistry_Soil_Fertilization__c= (upTarget.Chemistry_Soil_Fertilization__c != null && oldTarget.Chemistry_Soil_Fertilization__c == null)?upTarget.Chemistry_Soil_Fertilization__c:oldTarget.Chemistry_Soil_Fertilization__c;
				upsertarget.Complete_Protection_Suit__c= (upTarget.Complete_Protection_Suit__c != null && oldTarget.Complete_Protection_Suit__c == null)?upTarget.Complete_Protection_Suit__c:oldTarget.Complete_Protection_Suit__c;
				upsertarget.Conservation_Practices_Acequias__c= (upTarget.Conservation_Practices_Acequias__c != null && oldTarget.Conservation_Practices_Acequias__c == null)?upTarget.Conservation_Practices_Acequias__c:oldTarget.Conservation_Practices_Acequias__c;
				upsertarget.Conservation_Practices_Barreras__c= (upTarget.Conservation_Practices_Barreras__c != null && oldTarget.Conservation_Practices_Barreras__c == null)?upTarget.Conservation_Practices_Barreras__c:oldTarget.Conservation_Practices_Barreras__c;
				upsertarget.Conservation_Practices_Cajuelas__c= (upTarget.Conservation_Practices_Cajuelas__c != null && oldTarget.Conservation_Practices_Cajuelas__c == null)?upTarget.Conservation_Practices_Cajuelas__c:oldTarget.Conservation_Practices_Cajuelas__c;
				upsertarget.Conservation_Practices_Terrazas__c= (upTarget.Conservation_Practices_Terrazas__c != null && oldTarget.Conservation_Practices_Terrazas__c == null)?upTarget.Conservation_Practices_Terrazas__c:oldTarget.Conservation_Practices_Terrazas__c;
				upsertarget.Desuchering__c= (upTarget.Desuchering__c != null && oldTarget.Desuchering__c == null)?upTarget.Desuchering__c:oldTarget.Desuchering__c;
				upsertarget.Erosion_Control_Practices__c= (upTarget.Erosion_Control_Practices__c != null && oldTarget.Erosion_Control_Practices__c == null)?upTarget.Erosion_Control_Practices__c:oldTarget.Erosion_Control_Practices__c;
				upsertarget.Expansion_crop__c= (upTarget.Expansion_crop__c != null && oldTarget.Expansion_crop__c == null)?upTarget.Expansion_crop__c:oldTarget.Expansion_crop__c;
				upsertarget.Family_Backyard_Garden__c= (upTarget.Family_Backyard_Garden__c != null && oldTarget.Family_Backyard_Garden__c == null)?upTarget.Family_Backyard_Garden__c:oldTarget.Family_Backyard_Garden__c;
				upsertarget.Farm_Diversification__c= (upTarget.Farm_Diversification__c != null && oldTarget.Farm_Diversification__c == null)?upTarget.Farm_Diversification__c:oldTarget.Farm_Diversification__c;
				upsertarget.Foliar_Fert_Bayfolan_forte_1__c= (upTarget.Foliar_Fert_Bayfolan_forte_1__c != null && oldTarget.Foliar_Fert_Bayfolan_forte_1__c == null)?upTarget.Foliar_Fert_Bayfolan_forte_1__c:oldTarget.Foliar_Fert_Bayfolan_forte_1__c;
				upsertarget.Foliar_Fert_Bayfolan_forte_2__c= (upTarget.Foliar_Fert_Bayfolan_forte_2__c != null && oldTarget.Foliar_Fert_Bayfolan_forte_2__c == null)?upTarget.Foliar_Fert_Bayfolan_forte_2__c:oldTarget.Foliar_Fert_Bayfolan_forte_2__c;
				upsertarget.Foliar_Fert_Bayfolan_forte_3__c= (upTarget.Foliar_Fert_Bayfolan_forte_3__c != null && oldTarget.Foliar_Fert_Bayfolan_forte_3__c == null)?upTarget.Foliar_Fert_Bayfolan_forte_3__c:oldTarget.Foliar_Fert_Bayfolan_forte_3__c;
				upsertarget.Foliar_Fert_Borax_1__c= (upTarget.Foliar_Fert_Borax_1__c != null && oldTarget.Foliar_Fert_Borax_1__c == null)?upTarget.Foliar_Fert_Borax_1__c:oldTarget.Foliar_Fert_Borax_1__c;
				upsertarget.Foliar_Fert_Borax_2__c= (upTarget.Foliar_Fert_Borax_2__c != null && oldTarget.Foliar_Fert_Borax_2__c == null)?upTarget.Foliar_Fert_Borax_2__c:oldTarget.Foliar_Fert_Borax_2__c;
				upsertarget.Foliar_Fert_Borax_3__c= (upTarget.Foliar_Fert_Borax_3__c != null && oldTarget.Foliar_Fert_Borax_3__c == null)?upTarget.Foliar_Fert_Borax_3__c:oldTarget.Foliar_Fert_Borax_3__c;
				upsertarget.Foliar_Fert_Ferticafe_1__c= (upTarget.Foliar_Fert_Ferticafe_1__c != null && oldTarget.Foliar_Fert_Ferticafe_1__c == null)?upTarget.Foliar_Fert_Ferticafe_1__c:oldTarget.Foliar_Fert_Ferticafe_1__c;
				upsertarget.Foliar_Fert_Ferticafe_2__c= (upTarget.Foliar_Fert_Ferticafe_2__c != null && oldTarget.Foliar_Fert_Ferticafe_2__c == null)?upTarget.Foliar_Fert_Ferticafe_2__c:oldTarget.Foliar_Fert_Ferticafe_2__c;
				upsertarget.Foliar_Fert_Ferticafe_3__c= (upTarget.Foliar_Fert_Ferticafe_3__c != null && oldTarget.Foliar_Fert_Ferticafe_3__c == null)?upTarget.Foliar_Fert_Ferticafe_3__c:oldTarget.Foliar_Fert_Ferticafe_3__c;
				upsertarget.Foliar_Fert_Multicafe_1__c= (upTarget.Foliar_Fert_Multicafe_1__c != null && oldTarget.Foliar_Fert_Multicafe_1__c == null)?upTarget.Foliar_Fert_Multicafe_1__c:oldTarget.Foliar_Fert_Multicafe_1__c;
				upsertarget.Foliar_Fert_Multicafe_2__c= (upTarget.Foliar_Fert_Multicafe_2__c != null && oldTarget.Foliar_Fert_Multicafe_2__c == null)?upTarget.Foliar_Fert_Multicafe_2__c:oldTarget.Foliar_Fert_Multicafe_2__c;
				upsertarget.Foliar_Fert_Multicafe_3__c= (upTarget.Foliar_Fert_Multicafe_3__c != null && oldTarget.Foliar_Fert_Multicafe_3__c == null)?upTarget.Foliar_Fert_Multicafe_3__c:oldTarget.Foliar_Fert_Multicafe_3__c;
				upsertarget.Foliar_Fert_Sulfato_cobre_1__c= (upTarget.Foliar_Fert_Sulfato_cobre_1__c != null && oldTarget.Foliar_Fert_Sulfato_cobre_1__c == null)?upTarget.Foliar_Fert_Sulfato_cobre_1__c:oldTarget.Foliar_Fert_Sulfato_cobre_1__c;
				upsertarget.Foliar_Fert_Sulfato_cobre_2__c= (upTarget.Foliar_Fert_Sulfato_cobre_2__c != null && oldTarget.Foliar_Fert_Sulfato_cobre_2__c == null)?upTarget.Foliar_Fert_Sulfato_cobre_2__c:oldTarget.Foliar_Fert_Sulfato_cobre_2__c;
				upsertarget.Foliar_Fert_Sulfato_cobre_3__c= (upTarget.Foliar_Fert_Sulfato_cobre_3__c != null && oldTarget.Foliar_Fert_Sulfato_cobre_3__c == null)?upTarget.Foliar_Fert_Sulfato_cobre_3__c:oldTarget.Foliar_Fert_Sulfato_cobre_3__c;
				upsertarget.Foliar_Fert_Sulfato_hierro_1__c= (upTarget.Foliar_Fert_Sulfato_hierro_1__c != null && oldTarget.Foliar_Fert_Sulfato_hierro_1__c == null)?upTarget.Foliar_Fert_Sulfato_hierro_1__c:oldTarget.Foliar_Fert_Sulfato_hierro_1__c;
				upsertarget.Foliar_Fert_Sulfato_hierro_2__c= (upTarget.Foliar_Fert_Sulfato_hierro_2__c != null && oldTarget.Foliar_Fert_Sulfato_hierro_2__c == null)?upTarget.Foliar_Fert_Sulfato_hierro_2__c:oldTarget.Foliar_Fert_Sulfato_hierro_2__c;
				upsertarget.Foliar_Fert_Sulfato_hierro_3__c= (upTarget.Foliar_Fert_Sulfato_hierro_3__c != null && oldTarget.Foliar_Fert_Sulfato_hierro_3__c == null)?upTarget.Foliar_Fert_Sulfato_hierro_3__c:oldTarget.Foliar_Fert_Sulfato_hierro_3__c;
				upsertarget.Foliar_Fert_Sulfato_magnesio_1__c= (upTarget.Foliar_Fert_Sulfato_magnesio_1__c != null && oldTarget.Foliar_Fert_Sulfato_magnesio_1__c == null)?upTarget.Foliar_Fert_Sulfato_magnesio_1__c:oldTarget.Foliar_Fert_Sulfato_magnesio_1__c;
				upsertarget.Foliar_Fert_Sulfato_magnesio_2__c= (upTarget.Foliar_Fert_Sulfato_magnesio_2__c != null && oldTarget.Foliar_Fert_Sulfato_magnesio_2__c == null)?upTarget.Foliar_Fert_Sulfato_magnesio_2__c:oldTarget.Foliar_Fert_Sulfato_magnesio_2__c;
				upsertarget.Foliar_Fert_Sulfato_magnesio_3__c= (upTarget.Foliar_Fert_Sulfato_magnesio_3__c != null && oldTarget.Foliar_Fert_Sulfato_magnesio_3__c == null)?upTarget.Foliar_Fert_Sulfato_magnesio_3__c:oldTarget.Foliar_Fert_Sulfato_magnesio_3__c;
				upsertarget.Foliar_Fert_Sulfato_manganeso_1__c= (upTarget.Foliar_Fert_Sulfato_manganeso_1__c != null && oldTarget.Foliar_Fert_Sulfato_manganeso_1__c == null)?upTarget.Foliar_Fert_Sulfato_manganeso_1__c:oldTarget.Foliar_Fert_Sulfato_manganeso_1__c;
				upsertarget.Foliar_Fert_Sulfato_manganeso_2__c= (upTarget.Foliar_Fert_Sulfato_manganeso_2__c != null && oldTarget.Foliar_Fert_Sulfato_manganeso_2__c == null)?upTarget.Foliar_Fert_Sulfato_manganeso_2__c:oldTarget.Foliar_Fert_Sulfato_manganeso_2__c;
				upsertarget.Foliar_Fert_Sulfato_manganeso_3__c= (upTarget.Foliar_Fert_Sulfato_manganeso_3__c != null && oldTarget.Foliar_Fert_Sulfato_manganeso_3__c == null)?upTarget.Foliar_Fert_Sulfato_manganeso_3__c:oldTarget.Foliar_Fert_Sulfato_manganeso_3__c;
				upsertarget.Foliar_Fert_Sulfato_potasio_1__c= (upTarget.Foliar_Fert_Sulfato_potasio_1__c != null && oldTarget.Foliar_Fert_Sulfato_potasio_1__c == null)?upTarget.Foliar_Fert_Sulfato_potasio_1__c:oldTarget.Foliar_Fert_Sulfato_potasio_1__c;
				upsertarget.Foliar_Fert_Sulfato_potasio_2__c= (upTarget.Foliar_Fert_Sulfato_potasio_2__c != null && oldTarget.Foliar_Fert_Sulfato_potasio_2__c == null)?upTarget.Foliar_Fert_Sulfato_potasio_2__c:oldTarget.Foliar_Fert_Sulfato_potasio_2__c;
				upsertarget.Foliar_Fert_Sulfato_potasio_3__c= (upTarget.Foliar_Fert_Sulfato_potasio_3__c != null && oldTarget.Foliar_Fert_Sulfato_potasio_3__c == null)?upTarget.Foliar_Fert_Sulfato_potasio_3__c:oldTarget.Foliar_Fert_Sulfato_potasio_3__c;
				upsertarget.Foliar_Fert_Sulfato_Zinc_1__c= (upTarget.Foliar_Fert_Sulfato_Zinc_1__c != null && oldTarget.Foliar_Fert_Sulfato_Zinc_1__c == null)?upTarget.Foliar_Fert_Sulfato_Zinc_1__c:oldTarget.Foliar_Fert_Sulfato_Zinc_1__c;
				upsertarget.Foliar_Fert_Sulfato_Zinc_2__c= (upTarget.Foliar_Fert_Sulfato_Zinc_2__c != null && oldTarget.Foliar_Fert_Sulfato_Zinc_2__c == null)?upTarget.Foliar_Fert_Sulfato_Zinc_2__c:oldTarget.Foliar_Fert_Sulfato_Zinc_2__c;
				upsertarget.Foliar_Fert_Sulfato_Zinc_3__c= (upTarget.Foliar_Fert_Sulfato_Zinc_3__c != null && oldTarget.Foliar_Fert_Sulfato_Zinc_3__c == null)?upTarget.Foliar_Fert_Sulfato_Zinc_3__c:oldTarget.Foliar_Fert_Sulfato_Zinc_3__c;
				upsertarget.Gallinaza_Application__c= (upTarget.Gallinaza_Application__c != null && oldTarget.Gallinaza_Application__c == null)?upTarget.Gallinaza_Application__c:oldTarget.Gallinaza_Application__c;
				upsertarget.House__c= (upTarget.House__c != null && oldTarget.House__c == null)?upTarget.House__c:oldTarget.House__c;
				upsertarget.Identify_Erosion__c= (upTarget.Identify_Erosion__c != null && oldTarget.Identify_Erosion__c == null)?upTarget.Identify_Erosion__c:oldTarget.Identify_Erosion__c;
				upsertarget.Inputs_Record__c= (upTarget.Inputs_Record__c != null && oldTarget.Inputs_Record__c == null)?upTarget.Inputs_Record__c:oldTarget.Inputs_Record__c;
				upsertarget.Maintenance_Dryer__c= (upTarget.Maintenance_Dryer__c != null && oldTarget.Maintenance_Dryer__c == null)?upTarget.Maintenance_Dryer__c:oldTarget.Maintenance_Dryer__c;
				upsertarget.Maintenance_Fermentation_Area__c= (upTarget.Maintenance_Fermentation_Area__c != null && oldTarget.Maintenance_Fermentation_Area__c == null)?upTarget.Maintenance_Fermentation_Area__c:oldTarget.Maintenance_Fermentation_Area__c;
				upsertarget.Management_Herbs__c= (upTarget.Management_Herbs__c != null && oldTarget.Management_Herbs__c == null)?upTarget.Management_Herbs__c:oldTarget.Management_Herbs__c;
				upsertarget.Micro_Foliar_EM_comercial_1__c= (upTarget.Micro_Foliar_EM_comercial_1__c != null && oldTarget.Micro_Foliar_EM_comercial_1__c == null)?upTarget.Micro_Foliar_EM_comercial_1__c:oldTarget.Micro_Foliar_EM_comercial_1__c;
				upsertarget.Micro_Foliar_EM_comercial_2__c= (upTarget.Micro_Foliar_EM_comercial_2__c != null && oldTarget.Micro_Foliar_EM_comercial_2__c == null)?upTarget.Micro_Foliar_EM_comercial_2__c:oldTarget.Micro_Foliar_EM_comercial_2__c;
				upsertarget.Micro_Foliar_EM_comercial_3__c= (upTarget.Micro_Foliar_EM_comercial_3__c != null && oldTarget.Micro_Foliar_EM_comercial_3__c == null)?upTarget.Micro_Foliar_EM_comercial_3__c:oldTarget.Micro_Foliar_EM_comercial_3__c;
				upsertarget.Micro_Foliar_Lixiviado_lombricomposta_1__c= (upTarget.Micro_Foliar_Lixiviado_lombricomposta_1__c != null && oldTarget.Micro_Foliar_Lixiviado_lombricomposta_1__c == null)?upTarget.Micro_Foliar_Lixiviado_lombricomposta_1__c:oldTarget.Micro_Foliar_Lixiviado_lombricomposta_1__c;
				upsertarget.Micro_Foliar_Lixiviado_lombricomposta_2__c= (upTarget.Micro_Foliar_Lixiviado_lombricomposta_2__c != null && oldTarget.Micro_Foliar_Lixiviado_lombricomposta_2__c == null)?upTarget.Micro_Foliar_Lixiviado_lombricomposta_2__c:oldTarget.Micro_Foliar_Lixiviado_lombricomposta_2__c;
				upsertarget.Micro_Foliar_Lixiviado_lombricomposta_3__c= (upTarget.Micro_Foliar_Lixiviado_lombricomposta_3__c != null && oldTarget.Micro_Foliar_Lixiviado_lombricomposta_3__c == null)?upTarget.Micro_Foliar_Lixiviado_lombricomposta_3__c:oldTarget.Micro_Foliar_Lixiviado_lombricomposta_3__c;
				upsertarget.Micro_Foliar_preparados_localmente_1__c= (upTarget.Micro_Foliar_preparados_localmente_1__c != null && oldTarget.Micro_Foliar_preparados_localmente_1__c == null)?upTarget.Micro_Foliar_preparados_localmente_1__c:oldTarget.Micro_Foliar_preparados_localmente_1__c;
				upsertarget.Micro_Foliar_preparados_localmente_2__c= (upTarget.Micro_Foliar_preparados_localmente_2__c != null && oldTarget.Micro_Foliar_preparados_localmente_2__c == null)?upTarget.Micro_Foliar_preparados_localmente_2__c:oldTarget.Micro_Foliar_preparados_localmente_2__c;
				upsertarget.Micro_Foliar_preparados_localmente_3__c= (upTarget.Micro_Foliar_preparados_localmente_3__c != null && oldTarget.Micro_Foliar_preparados_localmente_3__c == null)?upTarget.Micro_Foliar_preparados_localmente_3__c:oldTarget.Micro_Foliar_preparados_localmente_3__c;
				upsertarget.Microorganisms_Foliar_Fertilization__c= (upTarget.Microorganisms_Foliar_Fertilization__c != null && oldTarget.Microorganisms_Foliar_Fertilization__c == null)?upTarget.Microorganisms_Foliar_Fertilization__c:oldTarget.Microorganisms_Foliar_Fertilization__c;
				upsertarget.MIPE_Alto_10_S_1__c= (upTarget.MIPE_Alto_10_S_1__c != null && oldTarget.MIPE_Alto_10_S_1__c == null)?upTarget.MIPE_Alto_10_S_1__c:oldTarget.MIPE_Alto_10_S_1__c;
				upsertarget.MIPE_Alto_10_S_2__c= (upTarget.MIPE_Alto_10_S_2__c != null && oldTarget.MIPE_Alto_10_S_2__c == null)?upTarget.MIPE_Alto_10_S_2__c:oldTarget.MIPE_Alto_10_S_2__c;
				upsertarget.MIPE_Alto_10_S_3__c= (upTarget.MIPE_Alto_10_S_3__c != null && oldTarget.MIPE_Alto_10_S_3__c == null)?upTarget.MIPE_Alto_10_S_3__c:oldTarget.MIPE_Alto_10_S_3__c;
				upsertarget.MIPE_Caldo_bordeles_1__c= (upTarget.MIPE_Caldo_bordeles_1__c != null && oldTarget.MIPE_Caldo_bordeles_1__c == null)?upTarget.MIPE_Caldo_bordeles_1__c:oldTarget.MIPE_Caldo_bordeles_1__c;
				upsertarget.MIPE_Caldo_bordeles_2__c= (upTarget.MIPE_Caldo_bordeles_2__c != null && oldTarget.MIPE_Caldo_bordeles_2__c == null)?upTarget.MIPE_Caldo_bordeles_2__c:oldTarget.MIPE_Caldo_bordeles_2__c;
				upsertarget.MIPE_Caldo_bordeles_3__c= (upTarget.MIPE_Caldo_bordeles_3__c != null && oldTarget.MIPE_Caldo_bordeles_3__c == null)?upTarget.MIPE_Caldo_bordeles_3__c:oldTarget.MIPE_Caldo_bordeles_3__c;
				upsertarget.MIPE_Caldo_Sulfocalcico_1__c= (upTarget.MIPE_Caldo_Sulfocalcico_1__c != null && oldTarget.MIPE_Caldo_Sulfocalcico_1__c == null)?upTarget.MIPE_Caldo_Sulfocalcico_1__c:oldTarget.MIPE_Caldo_Sulfocalcico_1__c;
				upsertarget.MIPE_Caldo_Sulfocalcico_2__c= (upTarget.MIPE_Caldo_Sulfocalcico_2__c != null && oldTarget.MIPE_Caldo_Sulfocalcico_2__c == null)?upTarget.MIPE_Caldo_Sulfocalcico_2__c:oldTarget.MIPE_Caldo_Sulfocalcico_2__c;
				upsertarget.MIPE_Caldo_Sulfocalcico_3__c= (upTarget.MIPE_Caldo_Sulfocalcico_3__c != null && oldTarget.MIPE_Caldo_Sulfocalcico_3__c == null)?upTarget.MIPE_Caldo_Sulfocalcico_3__c:oldTarget.MIPE_Caldo_Sulfocalcico_3__c;
				upsertarget.MIPE_Duet_1__c= (upTarget.MIPE_Duet_1__c != null && oldTarget.MIPE_Duet_1__c == null)?upTarget.MIPE_Duet_1__c:oldTarget.MIPE_Duet_1__c;
				upsertarget.MIPE_Duet_2__c= (upTarget.MIPE_Duet_2__c != null && oldTarget.MIPE_Duet_2__c == null)?upTarget.MIPE_Duet_2__c:oldTarget.MIPE_Duet_2__c;
				upsertarget.MIPE_Duet_3__c= (upTarget.MIPE_Duet_3__c != null && oldTarget.MIPE_Duet_3__c == null)?upTarget.MIPE_Duet_3__c:oldTarget.MIPE_Duet_3__c;
				upsertarget.MIPE_Opus_1__c= (upTarget.MIPE_Opus_1__c != null && oldTarget.MIPE_Opus_1__c == null)?upTarget.MIPE_Opus_1__c:oldTarget.MIPE_Opus_1__c;
				upsertarget.MIPE_Opus_2__c= (upTarget.MIPE_Opus_2__c != null && oldTarget.MIPE_Opus_2__c == null)?upTarget.MIPE_Opus_2__c:oldTarget.MIPE_Opus_2__c;
				upsertarget.MIPE_Opus_3__c= (upTarget.MIPE_Opus_3__c != null && oldTarget.MIPE_Opus_3__c == null)?upTarget.MIPE_Opus_3__c:oldTarget.MIPE_Opus_3__c;
				upsertarget.MIPE_Timorex_Gold_1__c= (upTarget.MIPE_Timorex_Gold_1__c != null && oldTarget.MIPE_Timorex_Gold_1__c == null)?upTarget.MIPE_Timorex_Gold_1__c:oldTarget.MIPE_Timorex_Gold_1__c;
				upsertarget.MIPE_Timorex_Gold_2__c= (upTarget.MIPE_Timorex_Gold_2__c != null && oldTarget.MIPE_Timorex_Gold_2__c == null)?upTarget.MIPE_Timorex_Gold_2__c:oldTarget.MIPE_Timorex_Gold_2__c;
				upsertarget.MIPE_Timorex_Gold_3__c= (upTarget.MIPE_Timorex_Gold_3__c != null && oldTarget.MIPE_Timorex_Gold_3__c == null)?upTarget.MIPE_Timorex_Gold_3__c:oldTarget.MIPE_Timorex_Gold_3__c;
				upsertarget.Organic_Arana_Roja_Control__c= (upTarget.Organic_Arana_Roja_Control__c != null && oldTarget.Organic_Arana_Roja_Control__c == null)?upTarget.Organic_Arana_Roja_Control__c:oldTarget.Organic_Arana_Roja_Control__c;
				upsertarget.Organic_Broca_Control__c= (upTarget.Organic_Broca_Control__c != null && oldTarget.Organic_Broca_Control__c == null)?upTarget.Organic_Broca_Control__c:oldTarget.Organic_Broca_Control__c;
				upsertarget.Organic_Fertilizer__c= (upTarget.Organic_Fertilizer__c != null && oldTarget.Organic_Fertilizer__c == null)?upTarget.Organic_Fertilizer__c:oldTarget.Organic_Fertilizer__c;
				upsertarget.Organic_Foliar_Fertilization__c= (upTarget.Organic_Foliar_Fertilization__c != null && oldTarget.Organic_Foliar_Fertilization__c == null)?upTarget.Organic_Foliar_Fertilization__c:oldTarget.Organic_Foliar_Fertilization__c;
				upsertarget.Organic_Llaga_Control__c= (upTarget.Organic_Llaga_Control__c != null && oldTarget.Organic_Llaga_Control__c == null)?upTarget.Organic_Llaga_Control__c:oldTarget.Organic_Llaga_Control__c;
				upsertarget.Organic_Ojo_de_Gallo_Control__c= (upTarget.Organic_Ojo_de_Gallo_Control__c != null && oldTarget.Organic_Ojo_de_Gallo_Control__c == null)?upTarget.Organic_Ojo_de_Gallo_Control__c:oldTarget.Organic_Ojo_de_Gallo_Control__c;
				upsertarget.Organic_Roya_Control__c= (upTarget.Organic_Roya_Control__c != null && oldTarget.Organic_Roya_Control__c == null)?upTarget.Organic_Roya_Control__c:oldTarget.Organic_Roya_Control__c;
				upsertarget.Organic_Soil_Fertilization__c= (upTarget.Organic_Soil_Fertilization__c != null && oldTarget.Organic_Soil_Fertilization__c == null)?upTarget.Organic_Soil_Fertilization__c:oldTarget.Organic_Soil_Fertilization__c;
				upsertarget.Pulping_Machine_Maintenance__c= (upTarget.Pulping_Machine_Maintenance__c != null && oldTarget.Pulping_Machine_Maintenance__c == null)?upTarget.Pulping_Machine_Maintenance__c:oldTarget.Pulping_Machine_Maintenance__c;
				upsertarget.Recepa_Block__c= (upTarget.Recepa_Block__c != null && oldTarget.Recepa_Block__c == null)?upTarget.Recepa_Block__c:oldTarget.Recepa_Block__c;
				upsertarget.Record_Cherry_Collection__c= (upTarget.Record_Cherry_Collection__c != null && oldTarget.Record_Cherry_Collection__c == null)?upTarget.Record_Cherry_Collection__c:oldTarget.Record_Cherry_Collection__c;
				upsertarget.Renewal_Coffee_Planting__c= (upTarget.Renewal_Coffee_Planting__c != null && oldTarget.Renewal_Coffee_Planting__c == null)?upTarget.Renewal_Coffee_Planting__c:oldTarget.Renewal_Coffee_Planting__c;
				upsertarget.Repair_Dryer__c= (upTarget.Repair_Dryer__c != null && oldTarget.Repair_Dryer__c == null)?upTarget.Repair_Dryer__c:oldTarget.Repair_Dryer__c;
				upsertarget.Repair_Fermentation_Area__c= (upTarget.Repair_Fermentation_Area__c != null && oldTarget.Repair_Fermentation_Area__c == null)?upTarget.Repair_Fermentation_Area__c:oldTarget.Repair_Fermentation_Area__c;
				upsertarget.Repair_Pulping_Machine__c= (upTarget.Repair_Pulping_Machine__c != null && oldTarget.Repair_Pulping_Machine__c == null)?upTarget.Repair_Pulping_Machine__c:oldTarget.Repair_Pulping_Machine__c;
				upsertarget.Roads_Maintenance__c= (upTarget.Roads_Maintenance__c != null && oldTarget.Roads_Maintenance__c == null)?upTarget.Roads_Maintenance__c:oldTarget.Roads_Maintenance__c;
				upsertarget.Sales_Record__c= (upTarget.Sales_Record__c != null && oldTarget.Sales_Record__c == null)?upTarget.Sales_Record__c:oldTarget.Sales_Record__c;
				upsertarget.Seedbed__c= (upTarget.Seedbed__c != null && oldTarget.Seedbed__c == null)?upTarget.Seedbed__c:oldTarget.Seedbed__c;
				upsertarget.Seedbed_Bourbon__c= (upTarget.Seedbed_Bourbon__c != null && oldTarget.Seedbed_Bourbon__c == null)?upTarget.Seedbed_Bourbon__c:oldTarget.Seedbed_Bourbon__c;
				upsertarget.Seedbed_Catimor__c= (upTarget.Seedbed_Catimor__c != null && oldTarget.Seedbed_Catimor__c == null)?upTarget.Seedbed_Catimor__c:oldTarget.Seedbed_Catimor__c;
				upsertarget.Seedbed_Catuai__c= (upTarget.Seedbed_Catuai__c != null && oldTarget.Seedbed_Catuai__c == null)?upTarget.Seedbed_Catuai__c:oldTarget.Seedbed_Catuai__c;
				upsertarget.Seedbed_Caturra__c= (upTarget.Seedbed_Caturra__c != null && oldTarget.Seedbed_Caturra__c == null)?upTarget.Seedbed_Caturra__c:oldTarget.Seedbed_Caturra__c;
				upsertarget.Seedbed_Pache__c= (upTarget.Seedbed_Pache__c != null && oldTarget.Seedbed_Pache__c == null)?upTarget.Seedbed_Pache__c:oldTarget.Seedbed_Pache__c;
				upsertarget.Seedbed_Sarchimor__c= (upTarget.Seedbed_Sarchimor__c != null && oldTarget.Seedbed_Sarchimor__c == null)?upTarget.Seedbed_Sarchimor__c:oldTarget.Seedbed_Sarchimor__c;
				upsertarget.Seedbed_Villa_Lobos__c= (upTarget.Seedbed_Villa_Lobos__c != null && oldTarget.Seedbed_Villa_Lobos__c == null)?upTarget.Seedbed_Villa_Lobos__c:oldTarget.Seedbed_Villa_Lobos__c;
				upsertarget.Selecting_Grain_Quality__c= (upTarget.Selecting_Grain_Quality__c != null && oldTarget.Selecting_Grain_Quality__c == null)?upTarget.Selecting_Grain_Quality__c:oldTarget.Selecting_Grain_Quality__c;
				upsertarget.Selective_Pruning__c= (upTarget.Selective_Pruning__c != null && oldTarget.Selective_Pruning__c == null)?upTarget.Selective_Pruning__c:oldTarget.Selective_Pruning__c;
				upsertarget.Shadow_Management__c= (upTarget.Shadow_Management__c != null && oldTarget.Shadow_Management__c == null)?upTarget.Shadow_Management__c:oldTarget.Shadow_Management__c;
				upsertarget.Soil_Amendment__c= (upTarget.Soil_Amendment__c != null && oldTarget.Soil_Amendment__c == null)?upTarget.Soil_Amendment__c:oldTarget.Soil_Amendment__c;
				upsertarget.Soil_Amendment_Bocashi__c= (upTarget.Soil_Amendment_Bocashi__c != null && oldTarget.Soil_Amendment_Bocashi__c == null)?upTarget.Soil_Amendment_Bocashi__c:oldTarget.Soil_Amendment_Bocashi__c;
				upsertarget.Soil_Amendment_Cal_dolomita__c= (upTarget.Soil_Amendment_Cal_dolomita__c != null && oldTarget.Soil_Amendment_Cal_dolomita__c == null)?upTarget.Soil_Amendment_Cal_dolomita__c:oldTarget.Soil_Amendment_Cal_dolomita__c;
				upsertarget.Soil_Amendment_Composta__c= (upTarget.Soil_Amendment_Composta__c != null && oldTarget.Soil_Amendment_Composta__c == null)?upTarget.Soil_Amendment_Composta__c:oldTarget.Soil_Amendment_Composta__c;
				upsertarget.Soil_Amendment_Lombricomposta__c= (upTarget.Soil_Amendment_Lombricomposta__c != null && oldTarget.Soil_Amendment_Lombricomposta__c == null)?upTarget.Soil_Amendment_Lombricomposta__c:oldTarget.Soil_Amendment_Lombricomposta__c;
				upsertarget.Soil_Amendment_Magnesita__c= (upTarget.Soil_Amendment_Magnesita__c != null && oldTarget.Soil_Amendment_Magnesita__c == null)?upTarget.Soil_Amendment_Magnesita__c:oldTarget.Soil_Amendment_Magnesita__c;
				upsertarget.Soil_Amendment_Sulfato_de_calcio__c= (upTarget.Soil_Amendment_Sulfato_de_calcio__c != null && oldTarget.Soil_Amendment_Sulfato_de_calcio__c == null)?upTarget.Soil_Amendment_Sulfato_de_calcio__c:oldTarget.Soil_Amendment_Sulfato_de_calcio__c;
				upsertarget.Soil_Amendment_Triple_cal__c= (upTarget.Soil_Amendment_Triple_cal__c != null && oldTarget.Soil_Amendment_Triple_cal__c == null)?upTarget.Soil_Amendment_Triple_cal__c:oldTarget.Soil_Amendment_Triple_cal__c;
				upsertarget.Soil_Analysis__c= (upTarget.Soil_Analysis__c != null && oldTarget.Soil_Analysis__c == null)?upTarget.Soil_Analysis__c:oldTarget.Soil_Analysis__c;
				upsertarget.Soil_Fert_Gallinaza_certificada_1__c= (upTarget.Soil_Fert_Gallinaza_certificada_1__c != null && oldTarget.Soil_Fert_Gallinaza_certificada_1__c == null)?upTarget.Soil_Fert_Gallinaza_certificada_1__c:oldTarget.Soil_Fert_Gallinaza_certificada_1__c;
				upsertarget.Soil_Fert_Gallinaza_certificada_2__c= (upTarget.Soil_Fert_Gallinaza_certificada_2__c != null && oldTarget.Soil_Fert_Gallinaza_certificada_2__c == null)?upTarget.Soil_Fert_Gallinaza_certificada_2__c:oldTarget.Soil_Fert_Gallinaza_certificada_2__c;
				upsertarget.Soil_Fert_Gallinaza_certificada_3__c= (upTarget.Soil_Fert_Gallinaza_certificada_3__c != null && oldTarget.Soil_Fert_Gallinaza_certificada_3__c == null)?upTarget.Soil_Fert_Gallinaza_certificada_3__c:oldTarget.Soil_Fert_Gallinaza_certificada_3__c;
				upsertarget.Soil_Fertilization_Bocashi_1__c= (upTarget.Soil_Fertilization_Bocashi_1__c != null && oldTarget.Soil_Fertilization_Bocashi_1__c == null)?upTarget.Soil_Fertilization_Bocashi_1__c:oldTarget.Soil_Fertilization_Bocashi_1__c;
				upsertarget.Soil_Fertilization_Bocashi_2__c= (upTarget.Soil_Fertilization_Bocashi_2__c != null && oldTarget.Soil_Fertilization_Bocashi_2__c == null)?upTarget.Soil_Fertilization_Bocashi_2__c:oldTarget.Soil_Fertilization_Bocashi_2__c;
				upsertarget.Soil_Fertilization_Bocashi_3__c= (upTarget.Soil_Fertilization_Bocashi_3__c != null && oldTarget.Soil_Fertilization_Bocashi_3__c == null)?upTarget.Soil_Fertilization_Bocashi_3__c:oldTarget.Soil_Fertilization_Bocashi_3__c;
				upsertarget.Soil_Fertilization_Composta_1__c= (upTarget.Soil_Fertilization_Composta_1__c != null && oldTarget.Soil_Fertilization_Composta_1__c == null)?upTarget.Soil_Fertilization_Composta_1__c:oldTarget.Soil_Fertilization_Composta_1__c;
				upsertarget.Soil_Fertilization_Composta_2__c= (upTarget.Soil_Fertilization_Composta_2__c != null && oldTarget.Soil_Fertilization_Composta_2__c == null)?upTarget.Soil_Fertilization_Composta_2__c:oldTarget.Soil_Fertilization_Composta_2__c;
				upsertarget.Soil_Fertilization_Composta_3__c= (upTarget.Soil_Fertilization_Composta_3__c != null && oldTarget.Soil_Fertilization_Composta_3__c == null)?upTarget.Soil_Fertilization_Composta_3__c:oldTarget.Soil_Fertilization_Composta_3__c;
				upsertarget.Soil_Fertilization_Gallinaza_certificada__c= (upTarget.Soil_Fertilization_Gallinaza_certificada__c != null && oldTarget.Soil_Fertilization_Gallinaza_certificada__c == null)?upTarget.Soil_Fertilization_Gallinaza_certificada__c:oldTarget.Soil_Fertilization_Gallinaza_certificada__c;
				upsertarget.Soil_Fertilization_KCl_1__c= (upTarget.Soil_Fertilization_KCl_1__c != null && oldTarget.Soil_Fertilization_KCl_1__c == null)?upTarget.Soil_Fertilization_KCl_1__c:oldTarget.Soil_Fertilization_KCl_1__c;
				upsertarget.Soil_Fertilization_KCl_2__c= (upTarget.Soil_Fertilization_KCl_2__c != null && oldTarget.Soil_Fertilization_KCl_2__c == null)?upTarget.Soil_Fertilization_KCl_2__c:oldTarget.Soil_Fertilization_KCl_2__c;
				upsertarget.Soil_Fertilization_KCl_3__c= (upTarget.Soil_Fertilization_KCl_3__c != null && oldTarget.Soil_Fertilization_KCl_3__c == null)?upTarget.Soil_Fertilization_KCl_3__c:oldTarget.Soil_Fertilization_KCl_3__c;
				upsertarget.Soil_Fertilization_KMag_1__c= (upTarget.Soil_Fertilization_KMag_1__c != null && oldTarget.Soil_Fertilization_KMag_1__c == null)?upTarget.Soil_Fertilization_KMag_1__c:oldTarget.Soil_Fertilization_KMag_1__c;
				upsertarget.Soil_Fertilization_KMag_2__c= (upTarget.Soil_Fertilization_KMag_2__c != null && oldTarget.Soil_Fertilization_KMag_2__c == null)?upTarget.Soil_Fertilization_KMag_2__c:oldTarget.Soil_Fertilization_KMag_2__c;
				upsertarget.Soil_Fertilization_KMag_3__c= (upTarget.Soil_Fertilization_KMag_3__c != null && oldTarget.Soil_Fertilization_KMag_3__c == null)?upTarget.Soil_Fertilization_KMag_3__c:oldTarget.Soil_Fertilization_KMag_3__c;
				upsertarget.Soil_Fertilization_KS_1__c= (upTarget.Soil_Fertilization_KS_1__c != null && oldTarget.Soil_Fertilization_KS_1__c == null)?upTarget.Soil_Fertilization_KS_1__c:oldTarget.Soil_Fertilization_KS_1__c;
				upsertarget.Soil_Fertilization_KS_2__c= (upTarget.Soil_Fertilization_KS_2__c != null && oldTarget.Soil_Fertilization_KS_2__c == null)?upTarget.Soil_Fertilization_KS_2__c:oldTarget.Soil_Fertilization_KS_2__c;
				upsertarget.Soil_Fertilization_KS_3__c= (upTarget.Soil_Fertilization_KS_3__c != null && oldTarget.Soil_Fertilization_KS_3__c == null)?upTarget.Soil_Fertilization_KS_3__c:oldTarget.Soil_Fertilization_KS_3__c;
				upsertarget.Soil_Fertilization_Lombricomposta_1__c= (upTarget.Soil_Fertilization_Lombricomposta_1__c != null && oldTarget.Soil_Fertilization_Lombricomposta_1__c == null)?upTarget.Soil_Fertilization_Lombricomposta_1__c:oldTarget.Soil_Fertilization_Lombricomposta_1__c;
				upsertarget.Soil_Fertilization_Lombricomposta_2__c= (upTarget.Soil_Fertilization_Lombricomposta_2__c != null && oldTarget.Soil_Fertilization_Lombricomposta_2__c == null)?upTarget.Soil_Fertilization_Lombricomposta_2__c:oldTarget.Soil_Fertilization_Lombricomposta_2__c;
				upsertarget.Soil_Fertilization_Lombricomposta_3__c= (upTarget.Soil_Fertilization_Lombricomposta_3__c != null && oldTarget.Soil_Fertilization_Lombricomposta_3__c == null)?upTarget.Soil_Fertilization_Lombricomposta_3__c:oldTarget.Soil_Fertilization_Lombricomposta_3__c;
				upsertarget.Soil_Fertilization_Nitrato_de_amonio_N_1__c= (upTarget.Soil_Fertilization_Nitrato_de_amonio_N_1__c != null && oldTarget.Soil_Fertilization_Nitrato_de_amonio_N_1__c == null)?upTarget.Soil_Fertilization_Nitrato_de_amonio_N_1__c:oldTarget.Soil_Fertilization_Nitrato_de_amonio_N_1__c;
				upsertarget.Soil_Fertilization_Nitrato_de_amonio_N_2__c= (upTarget.Soil_Fertilization_Nitrato_de_amonio_N_2__c != null && oldTarget.Soil_Fertilization_Nitrato_de_amonio_N_2__c == null)?upTarget.Soil_Fertilization_Nitrato_de_amonio_N_2__c:oldTarget.Soil_Fertilization_Nitrato_de_amonio_N_2__c;
				upsertarget.Soil_Fertilization_Nitrato_de_amonio_N_3__c= (upTarget.Soil_Fertilization_Nitrato_de_amonio_N_3__c != null && oldTarget.Soil_Fertilization_Nitrato_de_amonio_N_3__c == null)?upTarget.Soil_Fertilization_Nitrato_de_amonio_N_3__c:oldTarget.Soil_Fertilization_Nitrato_de_amonio_N_3__c;
				upsertarget.Soil_Fertilization_NK_1__c= (upTarget.Soil_Fertilization_NK_1__c != null && oldTarget.Soil_Fertilization_NK_1__c == null)?upTarget.Soil_Fertilization_NK_1__c:oldTarget.Soil_Fertilization_NK_1__c;
				upsertarget.Soil_Fertilization_NK_2__c= (upTarget.Soil_Fertilization_NK_2__c != null && oldTarget.Soil_Fertilization_NK_2__c == null)?upTarget.Soil_Fertilization_NK_2__c:oldTarget.Soil_Fertilization_NK_2__c;
				upsertarget.Soil_Fertilization_NK_3__c= (upTarget.Soil_Fertilization_NK_3__c != null && oldTarget.Soil_Fertilization_NK_3__c == null)?upTarget.Soil_Fertilization_NK_3__c:oldTarget.Soil_Fertilization_NK_3__c;
				upsertarget.Soil_Fertilization_NP_1__c= (upTarget.Soil_Fertilization_NP_1__c != null && oldTarget.Soil_Fertilization_NP_1__c == null)?upTarget.Soil_Fertilization_NP_1__c:oldTarget.Soil_Fertilization_NP_1__c;
				upsertarget.Soil_Fertilization_NP_2__c= (upTarget.Soil_Fertilization_NP_2__c != null && oldTarget.Soil_Fertilization_NP_2__c == null)?upTarget.Soil_Fertilization_NP_2__c:oldTarget.Soil_Fertilization_NP_2__c;
				upsertarget.Soil_Fertilization_NP_3__c= (upTarget.Soil_Fertilization_NP_3__c != null && oldTarget.Soil_Fertilization_NP_3__c == null)?upTarget.Soil_Fertilization_NP_3__c:oldTarget.Soil_Fertilization_NP_3__c;
				upsertarget.Soil_Fertilization_NPK_1__c= (upTarget.Soil_Fertilization_NPK_1__c != null && oldTarget.Soil_Fertilization_NPK_1__c == null)?upTarget.Soil_Fertilization_NPK_1__c:oldTarget.Soil_Fertilization_NPK_1__c;
				upsertarget.Soil_Fertilization_NPK_2__c= (upTarget.Soil_Fertilization_NPK_2__c != null && oldTarget.Soil_Fertilization_NPK_2__c == null)?upTarget.Soil_Fertilization_NPK_2__c:oldTarget.Soil_Fertilization_NPK_2__c;
				upsertarget.Soil_Fertilization_NPK_3__c= (upTarget.Soil_Fertilization_NPK_3__c != null && oldTarget.Soil_Fertilization_NPK_3__c == null)?upTarget.Soil_Fertilization_NPK_3__c:oldTarget.Soil_Fertilization_NPK_3__c;
				upsertarget.Soil_Fertilization_NPKMgB_1__c= (upTarget.Soil_Fertilization_NPKMgB_1__c != null && oldTarget.Soil_Fertilization_NPKMgB_1__c == null)?upTarget.Soil_Fertilization_NPKMgB_1__c:oldTarget.Soil_Fertilization_NPKMgB_1__c;
				upsertarget.Soil_Fertilization_NPKMgB_2__c= (upTarget.Soil_Fertilization_NPKMgB_2__c != null && oldTarget.Soil_Fertilization_NPKMgB_2__c == null)?upTarget.Soil_Fertilization_NPKMgB_2__c:oldTarget.Soil_Fertilization_NPKMgB_2__c;
				upsertarget.Soil_Fertilization_NPKMgB_3__c= (upTarget.Soil_Fertilization_NPKMgB_3__c != null && oldTarget.Soil_Fertilization_NPKMgB_3__c == null)?upTarget.Soil_Fertilization_NPKMgB_3__c:oldTarget.Soil_Fertilization_NPKMgB_3__c;
				upsertarget.Soil_Fertilization_NS_1__c= (upTarget.Soil_Fertilization_NS_1__c != null && oldTarget.Soil_Fertilization_NS_1__c == null)?upTarget.Soil_Fertilization_NS_1__c:oldTarget.Soil_Fertilization_NS_1__c;
				upsertarget.Soil_Fertilization_NS_2__c= (upTarget.Soil_Fertilization_NS_2__c != null && oldTarget.Soil_Fertilization_NS_2__c == null)?upTarget.Soil_Fertilization_NS_2__c:oldTarget.Soil_Fertilization_NS_2__c;
				upsertarget.Soil_Fertilization_NS_3__c= (upTarget.Soil_Fertilization_NS_3__c != null && oldTarget.Soil_Fertilization_NS_3__c == null)?upTarget.Soil_Fertilization_NS_3__c:oldTarget.Soil_Fertilization_NS_3__c;
				upsertarget.Soil_Fertilization_Urea_N_1__c= (upTarget.Soil_Fertilization_Urea_N_1__c != null && oldTarget.Soil_Fertilization_Urea_N_1__c == null)?upTarget.Soil_Fertilization_Urea_N_1__c:oldTarget.Soil_Fertilization_Urea_N_1__c;
				upsertarget.Soil_Fertilization_Urea_N_2__c= (upTarget.Soil_Fertilization_Urea_N_2__c != null && oldTarget.Soil_Fertilization_Urea_N_2__c == null)?upTarget.Soil_Fertilization_Urea_N_2__c:oldTarget.Soil_Fertilization_Urea_N_2__c;
				upsertarget.Soil_Fertilization_Urea_N_3__c= (upTarget.Soil_Fertilization_Urea_N_3__c != null && oldTarget.Soil_Fertilization_Urea_N_3__c == null)?upTarget.Soil_Fertilization_Urea_N_3__c:oldTarget.Soil_Fertilization_Urea_N_3__c;
				upsertarget.Warehouse__c= (upTarget.Warehouse__c != null && oldTarget.Warehouse__c == null)?upTarget.Warehouse__c:oldTarget.Warehouse__c;
				upsertarget.Wet_Mill__c= (upTarget.Wet_Mill__c != null && oldTarget.Wet_Mill__c == null)?upTarget.Wet_Mill__c:oldTarget.Wet_Mill__c;
				upsertarget.Work_Record__c= (upTarget.Work_Record__c != null && oldTarget.Work_Record__c == null)?upTarget.Work_Record__c:oldTarget.Work_Record__c;
				upsertarget.Zoca__c= (upTarget.Zoca__c != null && oldTarget.Zoca__c == null)?upTarget.Zoca__c:oldTarget.Zoca__c;
	    
				targetsToUpdate.add(upsertarget);
			}
			try {
			update targetsToUpdate;
			} catch (system.Dmlexception e) {
			    system.debug (e);
			}
		  }
	    }
}